python testing/benchmark-flatland.py -e encodings/multiple/grid/combined.lp -a 1
python testing/benchmark-flatland.py -e encodings/multiple/grid/combined.lp -a 5
python testing/benchmark-flatland.py -e encodings/multiple/grid/combined.lp -a 10
python testing/benchmark-flatland.py -e encodings/multiple/grid/combined.lp -a 15
python testing/benchmark-flatland.py -e encodings/multiple/grid/combined.lp -a 20
python testing/benchmark-flatland.py -e encodings/multiple/grid/combined.lp -a 25
python testing/benchmark-flatland.py -e encodings/multiple/grid/combined.lp -a 30
python testing/benchmark-flatland.py -e encodings/multiple/grid/combined.lp -a 35
python testing/benchmark-flatland.py -e encodings/multiple/grid/combined.lp -a 40
python testing/benchmark-flatland.py -e encodings/multiple/grid/combined.lp -a 45
python testing/benchmark-flatland.py -e encodings/multiple/grid/combined.lp -a 50

python testing/benchmark-flatland.py -e encodings/multiple/weighted/combined.lp -a 1
python testing/benchmark-flatland.py -e encodings/multiple/weighted/combined.lp -a 5
python testing/benchmark-flatland.py -e encodings/multiple/weighted/combined.lp -a 10
python testing/benchmark-flatland.py -e encodings/multiple/weighted/combined.lp -a 15
python testing/benchmark-flatland.py -e encodings/multiple/weighted/combined.lp -a 20
python testing/benchmark-flatland.py -e encodings/multiple/weighted/combined.lp -a 25
python testing/benchmark-flatland.py -e encodings/multiple/weighted/combined.lp -a 30
python testing/benchmark-flatland.py -e encodings/multiple/weighted/combined.lp -a 35
python testing/benchmark-flatland.py -e encodings/multiple/weighted/combined.lp -a 40
python testing/benchmark-flatland.py -e encodings/multiple/weighted/combined.lp -a 45
python testing/benchmark-flatland.py -e encodings/multiple/weighted/combined.lp -a 50